### ISSUE TITLE
smh doesnt compile

### ISSUE THREAD

**Issue by JackDanielJosephVarney** [krynv/passwordless#1]

**Comment by JackDanielJosephVarney** [comment]
its been 10 minutes and it hasnt been fixed, this is why the open source community sucks

**Comment by krynv** [comment]
fml

**Comment by krynv** [comment]
fixed with this commit https://github.com/krynv/passwordless/commit/9d5a28543d2f3d6eec0c239f3c9626d03f890716

**Comment by krynv** [comment]
tested and working fine on my end, closing issue
